### ISSUE TITLE
Starting server and mongoDB 

### ISSUE THREAD

**Issue by agrawalo** [rabira-hierpa/project-watchdog#15]
Can you also document how do we start the server? Code inside server folder?

**Comment by agrawalo** [comment]
MacBook-Air-2:server $ npm start app.js 

> projectwatchdog@1.0.0 start /Users/loki/project_watchdog/server
> nodemon app.js "app.js"

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js app.js`
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '../config/keys'
Require stack:
- /Users/lokeshagrawal/project_watchdog/server/routes/authentication.js
- /Users/lokeshagrawal/project_watchdog/server/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/lokeshagrawal/project_watchdog/server/routes/authentication.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/lokeshagrawal/project_watchdog/server/app.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lokeshagrawal/project_watchdog/server/routes/authentication.js',
    '/Users/lokeshagrawal/project_watchdog/server/app.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by rabira-hierpa** [comment]
Hi ,
Thank you for noticing my work.
Will take a look at the issue and get back to you as soon as I can.

**Comment by rabira-hierpa** [comment]
@agrawalo I've fixed the issue of starting the server. Please take a look at the updated readme files.
Closed on #73
