### ISSUE TITLE
When I Login and I set debugger it had displayed this error

### ISSUE THREAD

**Issue by sonnguyentb21** [rabira-hierpa/project-watchdog#84]
Log BE: 
 return Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (E:\Docs\project-watchdog\server\node_modules\express\lib\response.js:794:10)
    at ServerResponse.json (E:\Docs\project-watchdog\server\node_modules\express\lib\response.js:275:10)
    at ServerResponse.send (E:\Docs\project-watchdog\server\node_modules\express\lib\response.js:162:21)
    at E:\Docs\project-watchdog\server\routes\authentication.js:173:19
    at Layer.handle [as handle_request] (E:\Docs\project-watchdog\server\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Docs\project-watchdog\server\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (E:\Docs\project-watchdog\server\node_modules\express\lib\router\route.js:114:3)    at Layer.handle [as handle_request] (E:\Docs\project-watchdog\server\node_modules\express\lib\router\layer.js:95:5)

**Comment by rabira-hierpa** [comment]
@sonnguyentb21 I think this is mostly related to the express lib. I'll take a look and get back to you.

**Comment by rabira-hierpa** [comment]
@sonnguyentb21 I've made the fix and pushed the changes on PR #85
